# Generated by Django 3.2.9 on 2021-12-04 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugname', models.CharField(max_length=30)),
                ('isopioid', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prescribers',
            fields=[
                ('npi', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField(default=0)),
                ('credentials', models.ManyToManyField(to='portal.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')])),
                ('qty', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.drugs')),
                ('prescriberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.prescribers')),
            ],
        ),
        migrations.AddField(
            model_name='prescribers',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.state'),
        ),
    ]
