# Generated by Django 3.2.9 on 2021-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=14)),
                ('stateabbrev', models.CharField(max_length=2)),
                ('population', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
            ],
        ),
    ]
