# Generated by Django 3.2.8 on 2021-12-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_prescribers_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='id',
        ),
        migrations.AlterField(
            model_name='drugs',
            name='drugname',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
