# Generated by Django 3.2.9 on 2021-12-04 00:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescribers',
            fields=[
                ('npi', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('specialty', models.CharField(max_length=62)),
                ('isopioidprescriber', models.CharField(max_length=5)),
                ('totalprescriptions', models.IntegerField(default=0)),
                ('credentials', models.ManyToManyField(to='portal.Credentials')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.state')),
            ],
        ),
    ]
