# Generated by Django 3.2.9 on 2021-12-04 00:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_prescribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')])),
                ('qty', models.IntegerField(default=0)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.drugs')),
                ('prescriberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.prescribers')),
            ],
        ),
    ]
